name: Rate Limits All Versions

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.1
      - uses: actions/checkout@v3.5.0
      - uses: actions/checkout@v2.7.0
      - uses: actions/checkout@v3.4.0
      - uses: actions/checkout@v3.3.0
      - uses: actions/checkout@v2.6.0
      - uses: actions/checkout@v3.2.0
      - uses: actions/checkout@v2.5.0
      - uses: actions/checkout@v3.1.0
      - uses: actions/checkout@v3.0.2
      - uses: actions/checkout@v2.4.2
      - uses: actions/checkout@v3.0.1
      - uses: actions/checkout@v2.4.1
      - uses: actions/checkout@v3.0.0
      - uses: actions/checkout@v2.4.0
      - uses: actions/checkout@v2.3.5
      - uses: actions/checkout@v2.3.4
      - uses: actions/checkout@v2.3.3
      - uses: actions/checkout@v2.3.2
      - uses: actions/checkout@v2.3.1
      - uses: actions/checkout@v2.3.0
      - uses: actions/checkout@v2.2.0
      - uses: actions/checkout@v2.1.1
      - uses: actions/checkout@v2.1.0
      - uses: actions/checkout@v2.0.0
      - uses: actions/checkout@v2-beta
      - uses: actions/checkout@v1.0.0         