# This is a basic workflow to help you get started with Actions

name: Rate Limits

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      NB_LOOPS:
        description: 'Number of loops'
        required: true
        type: number
        default: 10
      INTERVAL_MILLI:
        description: 'Interval in millis'
        required: true
        type: number
        default: 1000

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Runs a javascript block to call the rate limit api
      - name: Get Rate Limits
        run: |
          curl -H "Accept: application/vnd.github.v3+json", -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit

      - name: Build
        run: |
          cd src
          npm install

      - name: List org repositories
        uses: actions/github-script@v3
        with:
          script: |
            const response = await github.repos.listForOrg({
              org: 'tdupoiron-org'
            });
            console.log(response);
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download actions
        run: |
          curl -H -verbose "Accept: application/vnd.github.v3+json", -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/actions/checkout/tarball/c85c95e3d7251135ab7dc9ce3241c5835cc595a9