name: Rate Limits All Versions

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.1
      - uses: actions/checkout@v3.5.0
      - uses: actions/checkout@v2.7.0
      - uses: actions/checkout@v3.4.0
      - uses: actions/checkout@v3.3.0
      - uses: actions/checkout@v2.6.0
      - uses: actions/checkout@v3.2.0
      - uses: actions/checkout@v2.5.0
      - uses: actions/checkout@v3.1.0
      - uses: actions/checkout@v3.0.2
      - uses: actions/checkout@v2.4.2
      - uses: actions/checkout@v3.0.1
      - uses: actions/checkout@v2.4.1
      - uses: actions/checkout@v3.0.0
      - uses: actions/checkout@v2.4.0
      - uses: actions/checkout@v2.3.5
      - uses: actions/checkout@v2.3.4
      - uses: actions/checkout@v2.3.3
      - uses: actions/checkout@v2.3.2
      - uses: actions/checkout@v2.3.1
      - uses: actions/checkout@v2.3.0
      - uses: actions/checkout@v2.2.0
      - uses: actions/checkout@v2.1.1
      - uses: actions/checkout@v2.1.0
      - uses: actions/checkout@v2.0.0
      - uses: actions/checkout@v2-beta
      - uses: actions/checkout@v1.0.0    
      - uses: actions/github-script@v2.1.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v2.1.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v6.4.1
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v4.2.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v5.2.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v3.2.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v6.4.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v6.3.3
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v6.3.2
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v6.3.1
        with:
          script: |
            console.log("Hello World")     
      - uses: actions/github-script@v6.3.0
        with:
          script: |
            console.log("Hello World")
            - uses: actions/github-script@v2.1.0
            with:
              script: |
                console.log("Hello World")
      - uses: actions/github-script@v6.2.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v6.1.1
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v5.1.1
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v6.1.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v6.0.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v5.1.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v5.0.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v4.1.1
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v4.1.0
        with:
          script: |
            console.log("Hello World")     
      - uses: actions/github-script@v4.0.2
        with:
          script: |
            console.log("Hello World")            
      - uses: actions/github-script@v4.0.1
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v4.0.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v3.1.1
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v3.1.0
        with:
          script: |
            console.log("Hello World")     
      - uses: actions/github-script@v3.0.2
        with:
          script: |
            console.log("Hello World")             
      - uses: actions/github-script@v3.0.1
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v3.0.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v2.0.1
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v2.0.0
        with:
          script: |
            console.log("Hello World")     
      - uses: actions/github-script@v1.1.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@v1.0.0
        with:
          script: |
            console.log("Hello World")
      - uses: actions/github-script@5d03ada4b0a753e9460b312e61cc4f8fdeacf163
        with:
          script: |
            console.log("Hello World")     
      - uses: actions/github-script@80a5e943b446817466ff17e8b61cb80848641ed6
        with:
          script: |
            console.log("Hello World")            